### ISSUE TITLE
Error running commands in README

### ISSUE THREAD

**Issue by noah-goodrich** [jnshubham/aws-glue-local-etl-docker#1]
I am BRAND new to Glue and found your post on towarddatascience for building a docker container for glue.

I am trying to run your container, but when running `docker run --rm jnshubham/glue_etl_local "gluepyspark"`, I receive this final message:

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.472 s
[INFO] Finished at: 2020-06-08T23:31:28Z
[INFO] ------------------------------------------------------------------------
rm: cannot remove '/glue/aws-glue-libs/jarsv1/javax.servlet-3.*': No such file or directory
mkdir: cannot create directory '/glue/aws-glue-libs/conf': File exists
/glue
```

Is this able to just be ignored?

**Comment by jnshubham** [comment]
This is just a warning and it should work perfectly fine. I'll work on this and mark this as warning while running. I will also update the docker image. Thanks for this.
